project:
  type: website

website:
  title: "LF2"
  sidebar:
    style: "docked"
    # search: true
    search: false     # bis auf Weiteres! Später true setzen (unveröffentlichte Dokumente nicht finden!)
    contents:
      - href: index.qmd
        text: Home
      - href: 01_Willkommen_Struktur.qmd
        text: 01 Willkommen zu LF2 - Themen und Zeitplan
      - href: 02a_Hardware.qmd
        text: 02 Hardware
      - href: 03a_Bedarfs-Anforderungsanalyse.qmd
        text: 03a Bedarfs- und Anforderungsanalyse
      - href: 03b_Istzustand-erfassen.qmd
        text: 03b Istzustand erfassen - Interview, Fragebogen, Beobachtung
      - href: 04_Nutzwertanalyse.qmd
        text: Nutzwertanalyse
      - href: 06a_Projektorga-Block1.qmd
        text: 05 Projektorganisation

format:
  revealjs:
    embed-resources: true
    include-after-body: libs/backlink.html
    css: libs/styles.css
    logo: libs/_Images/logo-AFBB.svg
    profile: public

profiles:
  internal:
    # zum Zeigen, mit Bildern
  public:
    # zum Veröffentlichen, ohne manche Bilder

publish:
  gh-pages: true
